[tool.ruff]
# enable all and disable a few via ignore below
select = ["ALL"]
extend-ignore = [
    "BLE",
    "COM",
    "EM",
    "FBT",
    "INP",
    "PTH",
    "S",
    "T20",
    "UP",
    "A003",
    "ANN101",
    "ANN102",
    "ANN401",
    "D105",
    "D107",
    "D205",
    "D212",
    "G004",
    "I001",
    "N806",
    "PTH123",
    "TRY003",
    "TRY400",
]
target-version = "py38"

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"*.pyi" = ["ALL"]
"__init__.py" = ["F401"]  # unused imports
"tests/*" = ["D", "ANN", "PLR2004"]
"scripts/*" = ["D"]
"examples/*" = ["D"]


[[tool.mypy.overrides]]
# ignore errors in modules with *.pyi file.
module = [
    "pam_vicon.o80",
]
ignore_errors = true


[[tool.mypy.overrides]]
module = [
    "o80",
    "scipy.*",
    "signal_handler",
    "spatial_transformation",
    "tennicam_client",
    "vicon_transformer.*",
]
ignore_missing_imports = true


[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
